# -*- coding: utf-8 -*-
"""nbc_sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WLeeEMdJUrByuqsEe-5q3BLvLctZlV-J
"""

import csv
import re
import math
import matplotlib.pyplot as plt

def load_stopwords(filepath="stopwords.txt"):
    with open(filepath, 'r', encoding='utf-8') as f:
        return f.read().splitlines()

def convert_text(text):
  lowercase_text = text.lower()
  special_char = r'[^a-z0-9\s]'
  result = re.sub(special_char, '', lowercase_text)
  return result

def handle_negation(tokens):
  negate_words = ["not", "never"]
  is_negated = False
  result = []
  for token in tokens:
    if is_negated:
      result.append(token + "_NEG")
      is_negated = False
    else:
      result.append(token)

    if token in negate_words:
      is_negated = True
  return result

def preprocess(text, stopwords):
    text = convert_text(text)
    tokens = text.split()
    tokens = [token for token in tokens if token not in stopwords]
    tokens = handle_negation(tokens)
    return tokens

def ngrams_generator (token, num):
  ngrams = []
  token_length = len(token)
  bounds = token_length - num + 1
  for i in range(bounds):
    ngrams.append(" ".join(token[i:i+num]))
  return ngrams

def task1():

  train_texts = []
  unigrams = []
  bigrams = []
  unigram_freq = {}
  bigram_freq = {}

  # Load stopwords
  stopwords = load_stopwords()

  # Load data
  with open("train.csv", 'r', encoding='utf-8') as f:
      reader = csv.reader(f)
      next(reader)
      for row in reader:
          train_texts.append(row[1])

  for text in train_texts:
    process_text = convert_text(text)
    tokenized_text = process_text.split()
    token_filter = [token for token in tokenized_text if token not in stopwords]
    negation_tokens = handle_negation(token_filter)
    unigrams.extend(negation_tokens)
    bigrams.extend(ngrams_generator(negation_tokens, 2))

  for unigram in unigrams:
    if unigram in unigram_freq:
      unigram_freq[unigram] += 1
    else:
      unigram_freq[unigram] = 1

  for bigram in bigrams:
    if bigram in bigram_freq:
      bigram_freq[bigram] += 1
    else:
      bigram_freq[bigram] = 1

  sorted_unigrams = sorted(unigram_freq.items(), key=lambda x: x[1], reverse=True)
  top_unigrams = [token for token, freq in sorted_unigrams[:700]]

  sorted_bigrams = sorted(bigram_freq.items(), key=lambda x: x[1], reverse=True)
  top_bigrams = [bigram for bigram, freq in sorted_bigrams[:300]]

  # Save to file for futher use
  with open("top_unigrams.txt", "w", encoding="utf-8") as f:
      for token in top_unigrams:
          f.write(token + "\n")

  with open("top_bigrams.txt", "w", encoding="utf-8") as f:
      for bigram in top_bigrams:
          f.write(bigram + "\n")

  print("Top 30 Unigrams:")
  for token, freq in sorted_unigrams[:30]:
      print(f"{token}: {freq}")

  print("\nTop 30 Bigrams:")
  for bigram, freq in sorted_bigrams[:30]:
      print(f"{bigram}: {freq}")

# 2
def extract_features(text, stopwords, top_unigrams, top_bigrams, mode="both"):
    tokens = preprocess(text, stopwords)
    features = set()

    if "unigram" in mode or mode == "both":
        features.update(token for token in tokens if token in top_unigrams)

    if "bigram" in mode or mode == "both":
        bigrams = ngrams_generator(tokens, 2)
        features.update(bigram for bigram in bigrams if bigram in top_bigrams)

    return features

# naive bayesian
def naive_bayes(X, y, vocab):
    class_counts = {0: 0, 1: 0}
    word_counts = {0: {}, 1: {}}

    for features, label in zip(X, y):
        class_counts[label] += 1
        for word in features:
            word_counts[label][word] = word_counts[label].get(word, 0) + 1
    return class_counts, word_counts

def log_probability_calc(features, vocab, class_count, word_counts_c, total_docs):
    log_prob = math.log(class_count / total_docs)
    total_words = sum(word_counts_c.values())
    V = len(vocab)

    for word in vocab:
        count = word_counts_c.get(word, 0)
        prob = (count + 1) / (total_words + V)
        if word in features:
            log_prob += math.log(prob)
        else:
            log_prob += math.log(1 - prob)

    return log_prob

def predict(features, vocab, class_counts, word_counts):
    total_docs = sum(class_counts.values())
    log_probs = {}

    for c in [0, 1]:
        log_prob = log_probability_calc(features, vocab, class_counts[c], word_counts[c], total_docs)
        log_probs[c] = log_prob

    return 1 if log_probs[1] > log_probs[0] else 0

def evaluate(y_true, y_pred):
    tp = 0
    tn = 0
    fp = 0
    fn = 0

    for yt, yp in zip(y_true, y_pred):
        if yt == 1 and yp == 1:
            tp += 1
        elif yt == 0 and yp == 0:
            tn += 1
        elif yt == 0 and yp == 1:
            fp += 1
        elif yt == 1 and yp == 0:
            fn += 1

    precision = tp / (tp + fp) if (tp + fp) else 0
    recall = tp / (tp + fn) if (tp + fn) else 0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) else 0
    return precision, recall, f1

def load_dataset(filepath):
    texts = []
    labels = []
    with open(filepath, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader)
        for row in reader:
            label = 1 if int(row[0]) == 5 else 0
            texts.append(row[1])
            labels.append(label)
    return texts, labels

def task2():
  vocab = set()
  X_train = []
  X_test = []
  preds = []

  stopwords = load_stopwords()

  train_texts, train_labels = load_dataset("train.csv")
  test_texts, test_labels = load_dataset("test.csv")

  with open("top_unigrams.txt", "r", encoding="utf-8") as f:
      top_unigrams = f.read().splitlines()
  with open("top_bigrams.txt", "r", encoding="utf-8") as f:
      top_bigrams = f.read().splitlines()

  for item in top_unigrams:
    vocab.add(item)
  for item in top_bigrams:
    vocab.add(item)

  for text in train_texts:
    X_train.append(extract_features(text, stopwords, top_unigrams, top_bigrams))

  for text in test_texts:
    X_test.append(extract_features(text, stopwords, top_unigrams, top_bigrams))

  class_counts, word_counts = naive_bayes(X_train, train_labels, vocab)

  for x in X_test:
    preds.append(predict(x, vocab, class_counts, word_counts))

  precision, recall, f1 = evaluate(test_labels, preds)
  print(f"\nPrecision: {precision:.4f}, Recall: {recall:.4f}, F1 Score: {f1:.4f}\n")

  # # Error Analysis (for task2)
  # for i in range(len(test_labels)):
  #     if test_labels[i] != preds[i]:
  #         print(f"FAIL (True: {test_labels[i]} Pred: {preds[i]}) -> {test_texts[i][:100]}...")
  #         # if i > 9:  # only show 10
  #         #     break

def task3_a():
    vocab = set()
    X_train = []
    X_test = []
    preds = []

    stopwords = load_stopwords()

    train_texts, train_labels = load_dataset("train.csv")
    test_texts, test_labels = load_dataset("test.csv")

    with open("top_unigrams.txt", "r", encoding="utf-8") as f:
        top_unigrams = f.read().splitlines()
    with open("top_bigrams.txt", "r", encoding="utf-8") as f:
        top_bigrams = f.read().splitlines()

    for item in top_unigrams:
      vocab.add(item)
    for item in top_bigrams:
      vocab.add(item)

    for text in test_texts:
      X_test.append(extract_features(text, stopwords, top_unigrams, top_bigrams))

    training_sizes = [0.1, 0.3, 0.5, 0.7, 1.0]
    f1_scores = []

    for size in training_sizes:
        cutoff = int(len(train_texts) * size)
        X_train = [extract_features(text, stopwords, top_unigrams, top_bigrams) for text in train_texts[:cutoff]]
        y_train = train_labels[:cutoff]

        class_counts, word_counts = train_naive_bayes(X_train, y_train, vocab)
        preds = [predict(x, vocab, class_counts, word_counts) for x in X_test]

        _, _, f1 = evaluate(test_labels, preds)
        f1_scores.append(f1)

    plt.plot([10,30,50,70,100], f1_scores, marker='o')
    plt.xlabel("Training Data (%)")
    plt.ylabel("F1 Score")
    plt.title("Learning Curve")
    plt.grid(True)
    plt.show()


def task3_b():
    stopwords = load_stopwords()
    top_unigrams, top_bigrams = load_features()

    train_texts, train_labels = load_dataset("train.csv")
    test_texts, test_labels = load_dataset("test.csv")

    sets = ["unigram", "bigram", "both"]
    results = {}

    for mode in sets:
        if mode == "unigram":
            vocab = set(top_unigrams)
        elif mode == "bigram":
            vocab = set(top_bigrams)
        else:
            vocab = set(top_unigrams) | set(top_bigrams)

        X_train = [extract_features(text, stopwords, top_unigrams, top_bigrams, mode=mode) for text in train_texts]
        X_test = [extract_features(text, stopwords, top_unigrams, top_bigrams, mode=mode) for text in test_texts]

        class_counts, word_counts = train_naive_bayes(X_train, train_labels, vocab)
        preds = [predict(x, vocab, class_counts, word_counts) for x in X_test]

        precision, recall, f1 = evaluate(test_labels, preds)
        results[mode] = (precision, recall, f1)

    print("\nAblation Study Results:")
    print(f"{'Feature Set':<10}  Precision  Recall  F1")
    for mode in sets:
        p, r, f = results[mode]
        print(f"{mode:<10}  {p:.4f}    {r:.4f}   {f:.4f}")

def main():
  task1()
  task2()
  task3_a()
  task3_b()



if __name__ == "__main__":
    main()